name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.build.outputs.date }}
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: build
        uses: ./.github/actions/build

  results:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: debug
        run: echo "::notice::${{ needs.build.outputs.date }}"

      - name: results
        run: echo "${{ needs.build.outputs.date }}"

  from_dockerfile:
    runs-on: ubuntu-latest
    steps:
      - run: ./build-image.sh
        working-directory: ./src

      - run: ./run.sh
        working-directory: ./src
        