name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.build.date }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        uses: ./.github/actions/build