name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.build.outputs.date }}

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: build
        uses: ./.github/actions/build

      - name: results
        run: echo "${{ needs.build.outputs.date }}"