name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.build.outputs.date }}
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: build
        uses: ./.github/actions/build

  results:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: results
        run: echo "${{ needs.build.outputs.date }}"